### ISSUE TITLE
ios模拟器提示加载失败

### ISSUE THREAD

**Issue by shihuacivis** [SyswinAE/weex-frame#11]
在ios模拟器中页面内容和图标都显示不出来了……但是点击tabbar切换的功能是可行的
![wechatimg1](https://cloud.githubusercontent.com/assets/6077019/24686743/4a640354-19e8-11e7-8e50-fcfb70d1c193.jpeg)

**Comment by chqfly** [comment]
遇到了同样的问题，怎么解决的呢？
