### ISSUE TITLE
全局变量.广播问题

### ISSUE THREAD

**Issue by zhangjianlin77** [SyswinAE/weex-frame#9]
想问下 这种方案存在以下问题,不知道你是怎么解决的

多个vue()之间如何广播（通知）。
多个vue之间，怎么处理全局变量（比如用户状态信息）
你项目中的bridge是如何使用的

**Comment by jinyb09017** [comment]
如何实现多页面之间相互通知，确实是个问题。求答疑

**Comment by walid1992** [comment]
正在考虑，在web端沿用spa模式，谢谢提议

**Comment by walid1992** [comment]
web端已支持spa单页模式，很高兴大家参与使用与且提建议~
